commit
romanchukegor/React_ToDo_Front pull request #1
Opened 2022-08-10 14:53 UTC by romanchukegor

2022-08-12 11:11 UTC, anrekov commented
Name commits, please
Like: Added list of todos, Fixed editTodo function and so on

2022-08-12 11:12 UTC, anrekov commented on my-app/src/App.js
> +          debugger;
do you really need it?

2022-08-12 11:16 UTC, anrekov commented on my-app/src/App.js
> +        {todos.map((element) => {
() => {return (<></>)}
===========>
() => (<></>)

2022-08-12 11:16 UTC, anrekov commented on my-app/src/App.js
> +        <TaskForm addTask={addTask} />
Add a blank line between same level components, pls

2022-08-12 11:18 UTC, anrekov commented on my-app/src/App.js
> +            elem._id === _id ? { ...elem, isCheck: !elem.isCheck } : { ...elem }
you don't need to copy elem in the second part of ternary operator

2022-08-12 11:20 UTC, anrekov commented on my-app/src/Components/Task.jsx
> +      const url = `http://localhost:8000/tasks/${_id}/text`;
patch can update any field with the same url
use: `http://localhost:8000/tasks/${_id}` for both

2022-08-12 11:21 UTC, anrekov commented on my-app/src/Components/Task.jsx
> +          const updateTodos = [...todos].map((element) => {
updateTodos sound like function
====>
updatedTodos suits more

2022-08-12 11:22 UTC, anrekov commented on my-app/src/Components/TaskForm.jsx
> +  return (
add an empty line before return, pls

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/App.js
> +import React, { useEffect, useState } from "react";
No need to import React, it is imported by default

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/App.js
> +function App() {
only routes should be here

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/App.js
> +    const url = "http://localhost:8000/tasks";
http://localhost:8000
Put it in constants

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/App.js
> +    axios.get(url).then((resp) => {
useEffect cannot be asynchronous. Move to separate function

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/App.js
> +      const allTasks = resp.data.allTasks;
and if instead of resp error?

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/App.js
> +          debugger;
why?

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/App.js
> +    if (input) {
what are you checking here?

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/App.js
> +  const addTask = (input) => {
the same errors as above. And what is an input? Input of what?

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/App.js
> +    axios.get(url).then((resp) => {
and use async/await

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/App.js
> +  const deleteTask = (_id) => {
the same errors as above.

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/App.js
> +  const deleteAllTasks = () => {
the same errors as above.

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/App.js
> +  const toggleTask = (_id, isCheck) => {
the same errors as above.

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/App.js
> +            elem._id === _id ? { ...elem, isCheck: !elem.isCheck } : { ...elem }
did not correct the previous comment

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/App.js
> +    <div className="App">
camelCase

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/App.js
> +      <div className="delete-all" onClick={() => deleteAllTasks()}>
Why is there an anonymous function here?

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/App.js
> +      <div className="delete-all" onClick={() => deleteAllTasks()}>
and why is it div?

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/Components/Task.jsx
> +import React from "react";
above wrote

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/Components/Task.jsx
> +    if (textEdit) {
above wrote

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/Components/Task.jsx
> +            <div onClick={() => updateTask(element._id)}>
why div??
this applies to all buttons

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/Components/Task.jsx
> +            <div onClick={() => cancelEdit()}>
anonymous function again?

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/Components/Task.jsx
> +              <img src={editImg} alt="" className="svg" />
what is the svg class?

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/Components/TaskForm.jsx
> +  const [input, setInput] = useState("");
rename

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/Components/TaskForm.jsx
> +import React from "react";
above wrote

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/Components/TaskForm.jsx
> +        <button>ADD TASK</button>
add type for buttons
if you add the correct type, you won't need preventDefault

2022-08-15 12:50 UTC, baklanovairina commented on my-app/src/index.css
> +
why are all the styles here? There should only be global

2022-08-18 13:13 UTC, baklanovairina commented on src/App.js
> +function App() {
arrow function

2022-08-18 13:13 UTC, baklanovairina commented on src/App.js
> +  const url = "http://localhost:8000";
put it in a file with constants

2022-08-18 13:13 UTC, baklanovairina commented on src/App.js
> +  const [todos, setTodos] = useState([]);
there should be no logic or components in App.js. Only routes

2022-08-18 13:13 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +      <div className="default-text">
default-text
use BEM, for example default-task-text

2022-08-18 13:13 UTC, baklanovairina commented on src/components/Task/Task.jsx
> +  const toggleTask = async (_id, isCheck) => {
toggleTask 
rename

2022-08-18 13:13 UTC, baklanovairina commented on src/components/Task/Task.jsx
> +    let res = await axios.patch(`${url}/tasks/${_id}/is-check`, {
why let?

/tasks/${_id}/check

2022-08-18 13:13 UTC, baklanovairina commented on src/components/Task/Task.jsx
> +    let res = await axios.patch(`${url}/tasks/${_id}/is-check`, {
all requests must be placed in a separate file "taskService" in the folder "service"

2022-08-18 13:13 UTC, baklanovairina commented on src/components/Task/Task.jsx
> +      ...todos.map((elem) =>
you have to work with the data received from backend

2022-08-18 13:13 UTC, baklanovairina commented on src/components/Task/Task.jsx
> +        <UpdateTaskButton
UpdateTaskButton
rename

2022-08-18 13:13 UTC, baklanovairina commented on src/components/Task/Task.jsx
> +          element={element}
why are you passing the whole task if you pass its text below? Pass separately id and text only

2022-08-18 13:13 UTC, baklanovairina commented on src/components/Task/Task.jsx
> +          setEditText={setEditText}
states should change only where they are created. That is, you can’t transfer state functions to other components, then you won’t track where changes in this state occur

2022-08-18 13:13 UTC, baklanovairina commented on src/components/Task/Task.jsx
> +          element={element}
same problem as above

2022-08-18 13:13 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +            className="check"
Work with class names. This applies to the entire project

2022-08-18 13:13 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +const DefaultTask = ({ toggleTask, setTaskEdit, deleteTask, element }) => {
element - what kind of element, not clear? Rename
better pass the checkbox and text separately

2022-08-18 13:13 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +        <div onClick={() => setTaskEdit(element._id)}>
why not a button?

2022-08-18 13:13 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +        <div onClick={() => deleteTask(element._id)}>
why not a button?

2022-08-18 13:13 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.scss
> +  .default-text {
indent one line between styles

2022-08-18 13:13 UTC, baklanovairina commented on src/components/DeleteAllButton/DeleteAllButton.jsx
> +const DeleteAllButton = ({ setTodos, url }) => {
do not change the states in other components and where does the url come from?

2022-08-18 13:13 UTC, baklanovairina commented on src/components/DeleteAllButton/DeleteAllButton.jsx
> +    <div className="delete-all" onClick={() => deleteAllTasks()}>
Why is there an anonymous function here?

2022-08-18 13:13 UTC, baklanovairina commented on src/components/Task/Task.jsx
> +import React from "react";
No need to import React, it is imported by default

2022-08-18 13:13 UTC, baklanovairina commented on src/components/Task/Task.jsx
> +const Task = ({ element, todos, setTodos, url }) => {
here are the same errors as in other components

in addition, the component of one task should not know about all tasks

2022-08-18 13:13 UTC, baklanovairina commented on src/components/Task/Task.jsx
> +  const [textEdit, setEditText] = useState("");
why textEdit? By the name of the component, it seems to be just a task

2022-08-18 13:13 UTC, baklanovairina commented on src/components/Task/Task.jsx
> +  const updateTask = async (_id) => {
all logic should be written where you have tasks to map

2022-08-18 13:13 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +const TaskForm = ({ todos, setTodos, url }) => {
all the same errors

2022-08-18 13:13 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +  const [userInput, setUserInput] = useState("");
where suddenly user ?

2022-08-18 13:13 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +        <button>ADD TASK</button>
add the correct type for the button and you won't need event.preventDefault();

2022-08-18 13:13 UTC, baklanovairina commented on src/components/UpdateTaskButton/UpdateTaskButton.jsx
> +const UpdateTaskButton = ({updateTask, cancelEdit, setEditText, textEdit, element}) => {
all the same errors

2022-11-02 08:59 UTC, baklanovairina requested changes

2022-11-02 08:59 UTC, baklanovairina commented on src/components/App/App.js
> +      <TODO url={url} />
зачем ты передаешь константу в пропсах??

2022-11-02 08:59 UTC, baklanovairina commented on src/components/App/App.js
> +import url from "../../constants";
используй везде абсолютные пути от src

2022-11-02 08:59 UTC, baklanovairina commented on src/components/App/App.js
> +      <TODO url={url} />
подключи роуты в App

2022-11-02 08:59 UTC, baklanovairina commented on src/components/App/App.scss
> +    display: flex;
что-то с табами

2022-11-02 08:59 UTC, baklanovairina commented on src/components/App/App.scss
> +    .header {
отступы между стилями в одну строку

2022-11-02 08:59 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +import "./DefaultTask.scss";
все scss файлы компонентов можно называть просто style

2022-11-02 08:59 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +  elementText,
почему бы вместо этих трех пропсов не передать сразу объект?

2022-11-02 08:59 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +  setTask,
что тут забыл setTask?

2022-11-02 08:59 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +        <button onClick={() => setTask(elementId)}>
ты не можешь изменять пропсы

2022-11-02 08:59 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.scss
> +  .default-task__text {
почему не используешь & ?

2022-11-02 08:59 UTC, baklanovairina commented on src/components/DeleteAllButton/DeleteAllButton.jsx
> +
лишняя пустая строка

2022-11-02 08:59 UTC, baklanovairina commented on src/components/DeleteAllButton/DeleteAllButton.scss
> +  button {
почему здесь общие стили?

2022-11-02 08:59 UTC, baklanovairina commented on src/components/EditTaskButton/EditTaskButton.jsx
> +import { useState } from "react";
порядок импорта нарушен, сначала библиотеки, потом уже картинки

2022-11-02 08:59 UTC, baklanovairina commented on src/components/EditTaskButton/EditTaskButton.jsx
> +  const [textEdit, setTextEdit] = useState("");
а почему пустая строка? Разве не должно быть последнее значение таска там быть?

2022-11-02 08:59 UTC, baklanovairina commented on src/components/EditTaskButton/EditTaskButton.jsx
> +      console.log("Error");
никаких консолей на фронте

2022-11-02 08:59 UTC, baklanovairina commented on src/components/EditTaskButton/EditTaskButton.jsx
> +  const handleSumbit = () => {
зачем тебе 2 функции добавления? Если у тебя форма, то только сабмит оставь, на кнопку не нужно вешать событие

2022-11-02 08:59 UTC, baklanovairina commented on src/components/EditTaskButton/EditTaskButton.jsx
> +      </form>
аа почему у тебя в форме только инпут и нет кнопки??

2022-11-02 08:59 UTC, baklanovairina commented on src/components/EditTaskButton/EditTaskButton.jsx
> +        <div>
как будто лишний контейнер

2022-11-02 08:59 UTC, baklanovairina commented on src/components/EditTaskButton/EditTaskButton.jsx
> +        <div >
и здесь

2022-11-02 08:59 UTC, baklanovairina commented on src/components/EditTaskButton/EditTaskButton.scss
> +  button {
опять общий стили

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TODO/TODO.jsx
> +import { useState } from "react";
эти строки можно объединить

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TODO/TODO.jsx
> +  const [taskEdit, setTaskEdit] = useState(null);
у тебя же вроде уже есть taskEdit в другом компоненте, в чем разница?

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TODO/TODO.jsx
> +    const res = await getAllTasksReq();
давай не писать Req в названиях сервисов

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TODO/TODO.jsx
> +    setTodos(allTasks);
эти строки можно объединить и не создавать лишние переменные

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TODO/TODO.jsx
> +    const res = await getAllTasksReq();
где обработчик ошибок?

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TODO/TODO.jsx
> +    const res = await addTaskReq(textInput);
везде не хватает обработччика ошибок

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TODO/TODO.jsx
> +    let res = await updateTaskReq(_id, text);
почему let?

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TODO/TODO.jsx
> +      if (element._id === _id) {
тебе нужно element._id сравнивать с тем, что приходит в res

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TODO/TODO.jsx
> +      return element;
а куда ты это возвращаешь и зачем?
и дальнейший код может не выполниться

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TODO/TODO.jsx
> +    await deleteTaskReq(_id);
не отлавливаешь ошибки, не првоеряешь, что приходит в запросе. А вдруг удаление на бэке не пройдет? Ты об этом не узнаешь, да еще и изменения сделаешь на фронте

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TODO/TODO.jsx
> +    await deleteAllTasksReq();
те же комменты, что и выше

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TODO/TODO.jsx
> +    await completeTaskReq(_id, isCheck);
тоже ничего не получаешь с бэка, почему?

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TODO/TODO.jsx
> +      ...todos.map((elem) =>
очень странный код стайл

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TODO/TODO.jsx
> +        elem._id === _id ? { ...elem, isCheck: !elem.isCheck } : { ...elem }
сравниваешь не с тем айди

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TODO/TODO.jsx
> +  const setTask = (_id) => {
так, если это не стейт, то лучше не называй ее через set, это путает

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TODO/TODO.jsx
> +const TODO = () => {
почему все буквы в названии заглавные?

2022-11-02 08:59 UTC, baklanovairina commented on src/components/Task/Task.jsx
> +const Task = ({
скорей всего это лишний компонент. Здесь ты только условный рендеринг делаешь, что можно сделать в другом. Да и еще пропсы передаешь, только чтобы их дальше передать

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +import { useState } from "react";
порядок импортов нарушен

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +const TaskForm = ({addTask}) => {
пробелы добавь

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +    console.log("Error")
выше писала

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +      <form onSubmit={handleSumbit}>
ну в общем тут те же ошибки, что были выше указаны

2022-11-02 08:59 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.scss
> +button {
и здесь тоже

2022-11-02 08:59 UTC, baklanovairina commented on src/constants.js
> +export default url
можно вместо этих двух строк просто сразу написать 
`export const url = "http://localhost:8000";`

2022-11-02 08:59 UTC, baklanovairina commented on src/index.scss
> +
много пустых строк

2022-11-02 08:59 UTC, baklanovairina commented on src/service/taskService.jsx
> +import axios from "axios";
порядок импортов

2022-11-02 08:59 UTC, baklanovairina commented on src/service/taskService.jsx
> +  text: text,
используй сокращенное написание

2022-11-02 08:59 UTC, baklanovairina commented on src/service/taskService.jsx
> +  isCheck: !isCheck,
ты не можешь в прям в запросе изменять значение, передавай уже нужное значение чекбокса

2022-11-07 09:07 UTC, baklanovairina requested changes

2022-11-07 09:07 UTC, baklanovairina commented on jsconfig.json
> +    "compilerOptions": {
по моему табы съехали

2022-11-07 09:07 UTC, baklanovairina commented on README.md
> +This section has moved here: [https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify](https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-
а тебе разве все нужно в этом файле?

2022-11-07 09:07 UTC, baklanovairina commented on src/components/App/App.js
> +import { Routes, Route } from "react-router-dom";
порядок: сначала библиотеки, потом комопненты

2022-11-07 09:07 UTC, baklanovairina commented on src/components/App/App.js
> +        <Route path="/" element={<Todo/>}/>
пробелы перед />
`<Route path="/" element={<Todo />} />`

2022-11-07 09:07 UTC, baklanovairina commented on src/components/App/style.scss
> +// @mixin flex() {
если это не нужно, удали

2022-11-07 09:07 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +import deleteImg from "../../images/delete.svg";
пути

2022-11-07 09:07 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +  const [isCheck, setIsCheck] = useState(false)
;

2022-11-07 09:07 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +    setIsCheck(!isCheck)
не !isCheck, а event используй
ты должен получать данные с инпута

2022-11-07 09:07 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +        <div>
этот контейнер точно нужен?

2022-11-07 09:07 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +          <input
табы

2022-11-07 09:07 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +            onChange = {handleChange}
удали пробелы

2022-11-07 09:07 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +          <form>
а зачем здесь форма??

2022-11-07 09:07 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +            onClick={handleSubmit}
зачем чекбоксу onClick, когда уже есть onChange?

2022-11-07 09:07 UTC, baklanovairina commented on src/components/DefaultTask/style.scss
> +.default-task__task-buttons {
вложенность используй максимально

2022-11-07 09:07 UTC, baklanovairina commented on src/components/DefaultTask/style.scss
> +  button {
общие стили не должны быть в отдельном компоненте

2022-11-07 09:07 UTC, baklanovairina commented on src/components/DeleteAllButton/DeleteAllButton.scss
> +  button {
и снова это общие стили

2022-11-07 09:07 UTC, baklanovairina commented on src/components/EditTask/EditTask.jsx
> +import doneImg from "../../images/done.svg";
порядок и пути поправь

2022-11-07 09:07 UTC, baklanovairina commented on src/components/EditTask/EditTask.jsx
> +    if (event.currentTarget.value === "") {
зачем ты здесь проверяешь на пустоту? У тебя валидация в handleSumbit должны быть

2022-11-07 09:07 UTC, baklanovairina commented on src/components/EditTask/EditTask.jsx
> +  const handleSumbit = () => {
handleSumbit - переименуй, как я понимаю эту функция обновления таска

2022-11-07 09:07 UTC, baklanovairina commented on src/components/EditTask/EditTask.jsx
> +      return;
вывод ошибки добавь

2022-11-07 09:07 UTC, baklanovairina commented on src/components/EditTask/EditTask.jsx
> +        <div style={{ color: "red", fontSize: "16px" }}>{textEditError}</div>
стили вынеси в отдельный файл для компонента ошибки

2022-11-07 09:07 UTC, baklanovairina commented on src/components/EditTask/EditTask.jsx
> +            <img src={doneImg} alt="" />
типы для кнопок пиши

2022-11-07 09:07 UTC, baklanovairina commented on src/components/EditTask/style.scss
> +@mixin edit() {
миксины не рекомендуется использовать

2022-11-07 09:07 UTC, baklanovairina commented on src/components/EditTask/style.scss
> +  form {
снова общие стили, пиши по БЭМу

2022-11-07 09:07 UTC, baklanovairina commented on src/components/EditTask/style.scss
> +  button {
и здесь тоже БЭМ

2022-11-07 09:07 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +      return;
где ошибка?

2022-11-07 09:07 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +    setTextInput(event.currentTarget.value);
выше писала

2022-11-07 09:07 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +    addTask(textInput);
зачем снова? и вообще handleSumbit? У тебя же есть addNewTask

2022-11-07 09:07 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +        <button type="submit" onClick={addNewTask}>
определись, ты или форму используешь и событие onSubmit, либо без формы и событие onClick на кнопке, а не все одновременно

2022-11-07 09:07 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +        {textError && <div style={{ color: "red" }}>{textError}</div>}
стили вынеси, выше писала

2022-11-07 09:07 UTC, baklanovairina commented on src/components/TaskForm/style.scss
> +@mixin size() {
выше писала

2022-11-07 09:07 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +import {
сначала сервисы, потом стили. Стили вообще в конце

2022-11-07 09:07 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +const TODO = () => {
почему все буквы заглавные у названия?

2022-11-07 09:07 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +        ...hasError,
а зачем ...hasError? Это же вроде не массив и не должен быть им

2022-11-07 09:07 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +      const updatedTodos = [...todos].map((element) => {
попробуй через find лучше, а то получается, что редактируется 1 таск, а проходимся мы все равно по всем

2022-11-07 09:07 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +      if (res.data.deletedCount === 1) {
а что будет если не = 1

2022-11-07 09:07 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +      if (res.data.deletedCount === 1) {
это же удаление всех тасков, так почему = 1?

2022-11-07 09:07 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +      setTodos([...todos.map((elem) => elem._id === res.data._id
тоже find используй

2022-11-07 09:07 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +  const [taskEdit, setTaskEdit] = useState(null);
если здесь хранится айди, то укажи это в названии, пожалуйста

2022-11-07 09:07 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +      setHasError({
И в каком случае этот catch сработает? Здесь нет даже запроса

2022-11-07 09:07 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +    } catch (err) {
этот catch тоже, что и выше

2022-11-07 09:07 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +          {todos.map((element) => {
а где key?

2022-11-07 09:07 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +      {!hasError.error && (
я не совсем поняла это условие. У тебя если есть ошибка, то тогда компоненты все исчезают и отображаются, только при отсутствии ошибки?

2022-11-07 09:07 UTC, baklanovairina commented on src/components/Todo/style.scss
> +  .task {
используй БЭМ

2022-11-07 09:07 UTC, baklanovairina commented on src/components/errorComponent/Error.jsx
> +    return (
табы проверь

2022-11-07 09:07 UTC, baklanovairina commented on src/components/errorComponent/Error.jsx
> +            <p style={{fontSize: "50px", color: "red"}}>Произошла ошибка... {errorText}</p>
стили в отдельной файле пишутся

2022-11-07 09:07 UTC, baklanovairina commented on src/service/taskService.jsx
> +import { url } from "../constants";
пути

2022-11-08 09:40 UTC, baklanovairina requested changes

2022-11-08 09:40 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +            checked={element.isCheck}
почему element.isCheck? Ты же для него стейт создал? Или стейт тебе не нужен?

2022-11-08 09:40 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +    setIsCheck(!isCheck);
раньше времени меняешь isCheck во всем приложении. У тебя же запрос ниже может не сработать и вернуть ошибку. 
Делай сначала запрос, проверяй, что приходит, и если не ошибка, то 
уже меняешь сетстейтом свой чексбокс везде

2022-11-08 09:40 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +          onClick={() => changeTask(element._id)}
типы для кнопок

2022-11-08 09:40 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +          <img src={editImg} alt="" className="default-task__image" />
больше двух атрибутов - переносим строки

2022-11-08 09:40 UTC, baklanovairina commented on src/components/DefaultTask/style.scss
> +  .default-task__text {
чего _& не используешь?

2022-11-08 09:40 UTC, baklanovairina commented on src/components/DefaultTask/style.scss
> +  }
отступ

2022-11-08 09:40 UTC, baklanovairina commented on src/components/DeleteAllButton/DeleteAllButton.jsx
> +    <div className="delete-all" onClick={deleteAllTasks}>
а почему у тебя див кликабельный, а не кнопка?

2022-11-08 09:40 UTC, baklanovairina commented on src/components/EditTask/EditTask.jsx
> +const EditTaskButton = ({ elementId, updateTask, cancelEdit, elementText }) => {
откуда взялось elementText? Мы работаем с тасками, а не с элементами

2022-11-08 09:40 UTC, baklanovairina commented on src/components/EditTask/EditTask.jsx
> +    } else {
зачем else?

2022-11-08 09:40 UTC, baklanovairina commented on src/components/EditTask/EditTask.jsx
> +      updateTask(elementId, textEdit);
проверяй не ошибка ли здесь приходит, прежде чем выполнять действия ниже

2022-11-08 09:40 UTC, baklanovairina commented on src/components/EditTask/style.scss
> +  .edit-form__input {
используй БЭМ и вложенность максимально вместе с &

2022-11-08 09:40 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +    addTask(textInput);
проверяй также не приходит ли ошибка прежде чем удалять ошибку и очищать инпут

2022-11-08 09:40 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +      {isError && <div className="add-form__error">{textError}</div>}
перенос строк

2022-11-08 09:40 UTC, baklanovairina commented on src/components/TaskForm/style.scss
> +.add-form__button {
все что и выше: используй вложенность

2022-11-08 09:40 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +} from "../../service/taskService";
везде должны быть абсолютные пути. Кроме тех случаев, где файлы лежат в одной папке

2022-11-08 09:40 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +  const [isError, setIsError] = useState(false);
а почему здесь эти два стейта не сделать объектом, как в другом компоненте?

2022-11-08 09:40 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +import Error from "components/errorComponent/Error";
components/errorComponent/Error"
почему названия папки и файла отличаются? Папка должна называться также как и компонент

2022-11-08 09:40 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +      debugger;
удали лучше из кода

2022-11-08 09:40 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +        return;
это зачем?

2022-11-08 09:40 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +        return;
это не нужно

2022-11-08 09:40 UTC, baklanovairina commented on src/components/Todo/style.scss
> +.content {
по названиям классов как будто стили не отсюда

2022-11-08 09:40 UTC, baklanovairina commented on src/components/errorComponent/Error.jsx
> +    <div>
ну тут мне  кажется точно див не нужен

2022-11-08 09:40 UTC, baklanovairina commented on src/constants.js
> +export const url = "http://localhost:8000";
/tasks тоже повторяется, поэтому можно внести в константу

2022-11-08 09:40 UTC, baklanovairina commented on src/setupTests.js
> +// jest-dom adds custom jest matchers for asserting on DOM nodes.
этот файл нужен для тестирования, поэтому пока его можно удалить

2022-11-08 11:45 UTC, romanchukegor commented on src/components/EditTask/EditTask.jsx
> +      updateTask(elementId, textEdit);
А как проверить? в try catch обернуть?

2022-11-09 10:20 UTC, baklanovairina requested changes

2022-11-09 10:20 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +  const handleChange = async () => {
async остался

2022-11-09 10:20 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +          <img src={editImg} alt="" className="default-task__image" />
не исправил код стайл

2022-11-09 10:20 UTC, baklanovairina commented on src/components/DefaultTask/DefaultTask.jsx
> +          <img src={deleteImg} alt="" className="default-task__image" />
и здесь код стайд - перенос строк

2022-11-09 10:20 UTC, baklanovairina commented on src/components/DefaultTask/style.scss
> +  }
что-то не хватает классов в файле. А если стилей нет, то зачем их писать в компоненте, например
className="default-task__image"

2022-11-09 10:20 UTC, baklanovairina commented on src/components/DeleteAllButton/DeleteAllButton.jsx
> +      <button className="delete-all__button" onClick={deleteAllTasks}>DELETE ALL</button>
тип кнопки

2022-11-09 10:20 UTC, baklanovairina commented on src/components/EditTask/EditTask.jsx
> +            onClick={updateEditTask}
тип

2022-11-09 10:20 UTC, baklanovairina commented on src/components/EditTask/EditTask.jsx
> +          <button onClick={cancelEdit} className="update-task__buttons__button">
тип

2022-11-09 10:20 UTC, baklanovairina commented on src/components/EditTask/EditTask.jsx
> +    } catch (error) {
толи не нужен try/catch, толи не хватает асинхронной функции

2022-11-09 10:20 UTC, baklanovairina commented on src/components/EditTask/EditTask.jsx
> +      {textEditError && <div className="text-error">{textEditError}</div>}
вопрос: а зачем мы тогда создавали компонент ошибки со своими стилями, если ты его не используешь?

2022-11-09 10:20 UTC, baklanovairina commented on src/components/EditTask/style.scss
> +
меня все же смущает, что у этого класса нет стилей, для чего он тогда?

2022-11-09 10:20 UTC, baklanovairina commented on src/components/Error/Error.jsx
> +      <p className="error-text">Произошла ошибка... {errorText}</p>
проверь табы

2022-11-09 10:20 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +          ...error,
уверен, что это нужно?

2022-11-09 10:20 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +      }
отступ добавь

2022-11-09 10:20 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +    } catch (error) {
и снова толи try/catch не нужен, то ли асинхронных действий не хватает, подумай, пожалуйста, что именно нужно сделать

2022-11-09 10:20 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +        ...error,
выше писала

2022-11-09 10:20 UTC, baklanovairina commented on src/components/TaskForm/style.scss
> +  flex-direction: column;
отступ добавь

2022-11-09 10:20 UTC, baklanovairina commented on src/components/TaskForm/TaskForm.jsx
> +        <div className="add-form__error">{error.textError}</div>
у тебя есть компонент для ошибки, используй его

2022-11-09 10:20 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +  console.log(todos);
удали консоль

2022-11-09 10:20 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +      if (res.data.deletedCount === 1) {
не исправил предыдущий коммент: запрос может быть успешным, но deletedCount не равен 1, ты это не учитываешь, такая ошибка в catch не попадет, так как запрос успешно прошел, но например ничего не удалил или слишком много удалил

2022-11-09 10:20 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +      if (res.data.acknowledged) {
лучше проверяй длину массива и количество удаленных элементов, просто что будет если элементы удаляться не все, но acknowledged будет тру

2022-11-09 10:20 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +  const cancelEdit = () => {
функция ради функции?

2022-11-09 10:20 UTC, baklanovairina commented on src/components/Todo/Todo.jsx
> +  const changeTask = (_id) => {
и здесь тоже?

2022-11-09 10:20 UTC, baklanovairina commented on src/constants.js
> +export const tasks = "tasks"
эм.. что? почему ты tasks отдельно написал?  Это так то часть url

2022-11-09 12:33 UTC, romanchukegor commented on src/components/DefaultTask/style.scss
> +  }
Для кнопки я указал rgba чтобы backround кнопки был прозрачным, но потом остаются границы и я убрал их с помощью border: 0, Можно так делать?

2022-11-16 10:24 UTC, merged